### ISSUE TITLE
Version tag

### ISSUE THREAD

**Issue by dgasmith** [aiqm/torchani#140]
Would it be possible to create a `__version__` attribute or similar so that individual runs can be reproduced? We usually recommend [versioneer](https://github.com/warner/python-versioneer) or similar for this kind of operation.

**Comment by dgasmith** [comment]
Yea, `versioneer` is starting to get a bit out of date, not sure what happened to the maintainer. I would assume that someone will fork it at some point. Anywho `versioneer` is "installed" so that a git repo carries it around and acts like a static dependancy. While it hasn't been updated in awhile it certainly does the job without issue and is used in many high profile projects, see the following two examples:
https://github.com/pandas-dev/pandas
https://github.com/dask/dask

Unfortunately not aware of alternatives for automatic versioning. There is the good old "by hand" approach, but it is easy to forget to update and has the downside of not being correct between releases.

**Comment by zasdfgbnm** [comment]
@dgasmith I will start using versioneer when I'm ready to release 0.2.

**Comment by zasdfgbnm** [comment]
This seems to be a good active alternative of versioneer: https://github.com/pypa/setuptools_scm/

**Comment by zasdfgbnm** [comment]
https://github.com/aiqm/torchani/pull/152

**Comment by zasdfgbnm** [comment]
@dgasmith I'm done with this using setuptools_scm. I'm closing this now. Feel free to reopen if you have further concern.
