### ISSUE TITLE
nnp_training fails due to corrupt .h5 files when using git clone 

### ISSUE THREAD

**Issue by mpwaller** [aiqm/torchani#168]
hi @zasdfgbnm, 

I think the dataset .h5 files:

- https://github.com/aiqm/torchani/blob/master/dataset/ani_gdb_s01.h5 
- https://github.com/aiqm/torchani/blob/master/dataset/ani_gdb_s02.h5
- https://github.com/aiqm/torchani/blob/master/dataset/ani_gdb_s03.h5
- https://github.com/aiqm/torchani/blob/master/dataset/ani_gdb_s04.h5

are corrupted when I use:

 `git clone https://github.com/aiqm/torchani.git`

I then installed torchani, and tested the energy_force.py script successfully.

But when I run:

`python nnp_training.py`

I get an error:

```
Error:
 File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

```
To solve the problem:
I download the four individual .h5 files manually from the Github website using the download button.
I then copied the files to the dataset folder.
Then the training script works as expected.

I am using:
    - Mac OS X 10.14.2
    - anaconda3
    - Python 3.7.2
    - torchani.__version__ = '0.2.2'
    - torch.__version__ = '1.0.0.dev20190214'
    - h5py.__version__ = '2.9.0'

**Comment by zasdfgbnm** [comment]
Hi @mpwaller, this is because, those files are stored in [Git LFS](https://git-lfs.github.com/), if your system didn't install git-lfs then those files would appear as a text file storing a pointer to the LFS system when you checkout the repository. You could fix this by installing git-lfs, and then
```
git lfs pull
```

Let me know if this solves your problem.

**Comment by mpwaller** [comment]
Excellent, I can confirm that running

` brew install git-lfs`

followed by 

`git lfs install`

allowed me to get the datasets correctly when I then used

`git clone https://github.com/aiqm/torchani.git`

Many thanks for pointing out the underlying problem.
