### ISSUE TITLE
non-consistent energies and forces in qrefine branch

### ISSUE THREAD

**Issue by mpwaller** [aiqm/torchani#170]
Hi @zasdfgbnm 

I get a different energy every time I use the energy_force.py example in the qrefine branch of torchani.

('Energy:', -40.30905532836914)
('Energy:', -40.434627532958984)
('Energy:', -40.549381256103516)
('Energy:', -40.627140045166016)
('Energy:', -40.549705505371094)
('Energy:', -40.49227523803711)

This is using phenix.python which is built on python 2.7.15

To ensure phenix.python was not causing the problem, I used a conda environment with python 2.7.3

('Energy:', -40.51961135864258)
('Energy:', -40.46982955932617)

In comparison, the latest version of torchani running on python 3.7.2 leads to consistent energies when I run energy_force.py:

Energy: -40.425621032714844
Energy: -40.425621032714844
Energy: -40.425621032714844

**Comment by zasdfgbnm** [comment]
Hi @mpwaller I see this issue. I am pretty busy until Thursday. I will start working on back porting TorchANI master branch inference code to python 2 and delete the qrefine branch after then.

**Comment by mpwaller** [comment]
Hi @zasdfgbnm many thanks.

**Comment by zasdfgbnm** [comment]
https://github.com/aiqm/torchani/issues/113

**Comment by zasdfgbnm** [comment]
fixed
