### ISSUE TITLE
Pickle File loading failure in tests

### ISSUE THREAD

**Issue by amrhamedp** [aiqm/torchani#271]
Hi,
I was trying to load pickle files in tests and i got the following error:
invalid load key, 'v'.

in
```python
datafile = os.path.join(path, 'test_data/ANI1_subset/{}'.format(i))
            with open(datafile, 'rb') as f:
                coordinates, species, expected_radial, expected_angular, _, _ \
                    = pickle.load(f)
```

**Comment by farhadrgh** [comment]
Hi, 
The following snippet was successfully executed and returned the correct dimensions, confirming the files have the right content. These pickle files are stored in git lfs, and if you didn't install it, you would get a text placeholder. Please install `git-lfs` and do `git lfs pull`.

```python
for i in range(97): 
    coordinates, species, expected_radial, expected_angular, _, _ = pickle.load(open(f'{i}', 'rb'))
    print(coordinates.shape, species.shape, expected_radial.shape, expected_angular.shape)
```

**Comment by zasdfgbnm** [comment]
@amrhamedp Could you please try `git lfs pull` again? We were out of quota last month.

**Comment by amrhamedp** [comment]
thank u 
It works now
