### ISSUE TITLE
Pytorch Lightning as a back-end

### ISSUE THREAD

**Issue by williamFalcon** [aiqm/torchani#277]
Hi! check out Pytorch Lightning as an option for your backend! We're looking for awesome project implemented in Lightning.

Your project will be really easy to maintain on Lightning!

https://github.com/williamFalcon/pytorch-lightning

**Comment by zasdfgbnm** [comment]
Hi @williamFalcon, we are welcome on having lightning as a backend. But currently, we don't have enough man-power to work on it. It is welcome if someone would like to work on it!

**Comment by zasdfgbnm** [comment]
We've decided not to include any high-level library inside TorchANI. How to train a model should be something that our users do. We just maintain the toolkits for users to build their model.
