### ISSUE TITLE
Periodic boundary conditions in torchANI

### ISSUE THREAD

**Issue by wiederm** [aiqm/torchani#301]
Dear developers!

I have noticed that the energy calculation using pbc is much slower than without pbc and uses much more memory (~10GB RAM for ~ 2500 atoms on a single CPU). I have plotted the time of a single energy evaluation with/without pbc for a rectangular waterbox vs the number of atoms in the system (always on a single CPU):
![image](https://user-images.githubusercontent.com/31651017/63885429-a2070a00-c9d8-11e9-93a4-bbb829c86ee9.png)
![image](https://user-images.githubusercontent.com/31651017/63893713-337f7780-c9eb-11e9-9a45-9e332ca8035d.png)

The plot was generated using torch 1.1.0.dev20190521 and torchani 0.8, the code can be found here: https://gist.github.com/wiederm/699c3f119d25ebd80fcdc7affdb89d64

Is this behaviour expected? Is there a way to get around it?

**Comment by farhadrgh** [comment]
Hi,
Yes, excessive memory usage and timing for energy evaluation using PBC is expected behavior. We are adding TorchScript compatibility (in #303) that might improve the performance for these evaluations.

**Comment by farhadrgh** [comment]
I am closing this right now. Feel free to reopen or continue the discussion if you have further questions.
