### ISSUE TITLE
Bring badges back for GitHub Actions

### ISSUE THREAD

**Issue by zasdfgbnm** [aiqm/torchani#320]
Things like below:
[![Actions Status](https://github.com/aiqm/torchani/workflows/docs/badge.svg)](https://github.com/aiqm/torchani/actions)
```markdown
[![Actions Status](https://github.com/aiqm/torchani/workflows/docs/badge.svg)](https://github.com/aiqm/torchani/actions)
```

@farhadrgh Could you help on this after https://github.com/aiqm/torchani/pull/317 get merged?

**Comment by farhadrgh** [comment]
Done!
