### ISSUE TITLE
Correctness of convert_pair_index function

### ISSUE THREAD

**Issue by zubatyuk** [aiqm/torchani#351]
Could someone explain where 8.0 came from in torchani.aev.convert_pair_index? Is it correct for any number of species in the model?

def convert_pair_index(index):
...
    n = (torch.sqrt(1.0 + 8.0 * index.to(torch.float)) - 1.0) / 2.0

**Comment by zasdfgbnm** [comment]
This is the solution of `N * (N + 1) / 2 <= i`

**Comment by zubatyuk** [comment]
Thanks!
