### ISSUE TITLE
Build dataset

### ISSUE THREAD

**Issue by njzjz** [aiqm/torchani#360]
Hi,
Is it possible to build my own dataset via `torchani`? Is it necessary to use the built-in ANI dataset to train models? I did not find any information in the [document](https://aiqm.github.io/torchani-test-docs/).

Thanks.

**Comment by farhadrgh** [comment]
Hi, TorchANI provides tools for inference and testing of ANI NNPs. Would you please clarify what do you mean by "build my own dataset"?

**Comment by njzjz** [comment]
In [this page](https://aiqm.github.io/torchani-test-docs/examples/nnp_training_force.html) the example uses `dataset/ani-1x/sample.h5` as the dataset. Is it possible to use my own data (energy and forces) here?

**Comment by farhadrgh** [comment]
Yes, you can create your dataset and use it for training (not with TorchANI though) as long as each entry has the same keys as the sample HDF5 datasets. This should be done using libraries like h5py. 

The required keys for compatible datasets are: `coordinates`, `species`, `energies`, and `forces`.

**Comment by zasdfgbnm** [comment]
@njzjz You can have your own dataset in any format. But our dataset loader only supports the hdf5 we are using, as @farhadrgh mentioned, they should have have the same key as our format. But using our data loader is not mandatory, and you can always load your data in your favorite way, convert it to PyTorch tensors, and feed it to your training pipeline.

**Comment by njzjz** [comment]
I see. Thank you!
