### ISSUE TITLE
Documentation on units

### ISSUE THREAD

**Issue by peastman** [aiqm/torchani#388]
I can't find any documentation on the units system used by torchani.  If I create a model, for example as

```python
model = torchani.models.ANI1ccx()
```

what units does it expect the input coordinates to be in?  What units does it return the energy in?

Thanks!

**Comment by zasdfgbnm** [comment]
coordinates are in angstrom, energies are in Hartree, we will fix the document soon

**Comment by peastman** [comment]
Thanks!

**Comment by peastman** [comment]
You're sure the energy is really Hartree, not Hartree/mol?

**Comment by peastman** [comment]
Never mind.  You're right.
