### ISSUE TITLE
Vibrational Frequencies

### ISSUE THREAD

**Issue by saeid0021** [aiqm/torchani#406]
Hello everyone,

I'm trying to do some frequency calculation using ` torchani.utils.hessian` and `ase.vibrations.Vibration`.
but I found some differences in TorchANI and ASE frequencies.
Why is there such a deviation? Which one is more accurate?

Regards,

**Comment by farhadrgh** [comment]
Hi Saeid, 
The derivatives are being calculated analytically by TorchANI. But ASE calculates them numerically.
Thanks,
