### ISSUE TITLE
Error converting model to TorchScript

### ISSUE THREAD

**Issue by peastman** [aiqm/torchani#407]
I'm using TorchANI with the PyTorch plugin for OpenMM (https://github.com/peastman/openmm-torch).  I just updated to the latest TorchANI code, and some change made in the last few months has broken my code.  To use the OpenMM plugin, I need to convert the model to TorchScript and save it to a file.  And in fact the following still works:

```python
model = torchani.models.ANI1ccx()
module = torch.jit.script(model[0])
```

But the plugin requires the inputs and outputs to have a slightly different format and units, so I created a class to act as an adapter:

```python
class ANIForce(torch.nn.Module):

    def __init__(self, model, species):
        super(ANIForce, self).__init__()
        self.model = model
        self.species = species
    
    def forward(self, positions):
        _, energy = self.model((self.species, 10.0*positions.unsqueeze(0)))
        return 2625.5000885335317*energy

force = ANIForce(model[0], species)
module = torch.jit.script(force)
```

Previously this worked, but after updating to the latest TorchANI code it throws an exception:

```
RuntimeError: 
Module '_ConstModuleList' has no attribute 'forward' :
at modelPdb.py:30:20
    def forward(self, positions):
        _, energy = self.model((self.species, 10.0*positions.unsqueeze(0)))
                    ~~~~~~~~~~ <--- HERE
        return 2625.5000885335317*energy
```

Can you provide advice on what I need to do to fix it?

**Comment by zasdfgbnm** [comment]
Hi @peastman,

I just tested the following code:

```python
import torch
import torchani
print(torch.__version__)
print(torchani.__version__)

model = torchani.models.ANI1ccx()
module = torch.jit.script(model[0])
print(module.graph)

class ANIForce(torch.nn.Module):

    def __init__(self, model, species):
        super(ANIForce, self).__init__()
        self.model = model
        self.species = species

    def forward(self, positions):
        _, energy = self.model((self.species, 10.0*positions.unsqueeze(0)))
        return 2625.5000885335317*energy

force = ANIForce(model[0], torch.zeros(1, 5))
module = torch.jit.script(force)
print(module.graph)
```

and seems to be working well with output:

```
1.5.0a0+0c91d4c
1.0.2.dev29+gd32081e
graph(%self : __torch__.torchani.nn.Sequential,
      %input_.1 : (Tensor, Tensor),
      %cell.1 : Tensor?,
      %pbc.1 : Tensor?):
  %5 : __torch__.torchani.aev.AEVComputer = prim::GetAttr[name="0"](%self)
  %7 : __torch__.torchani.nn.ANIModel = prim::GetAttr[name="1"](%self)
  %9 : __torch__.torchani.utils.EnergyShifter = prim::GetAttr[name="2"](%self)
  %input_.3 : NamedTuple(species : Tensor, aevs : Tensor) = prim::CallMethod[name="forward"](%5, %input_.1, %cell.1, %pbc.1) # /home/xgao/torchani/torchani/nn.py:99:21
  %input_.5 : NamedTuple(species : Tensor, energies : Tensor) = prim::CallMethod[name="forward"](%7, %input_.3, %cell.1, %pbc.1) # /home/xgao/torchani/torchani/nn.py:99:21
  %input_.7 : NamedTuple(species : Tensor, energies : Tensor) = prim::CallMethod[name="forward"](%9, %input_.5, %cell.1, %pbc.1) # /home/xgao/torchani/torchani/nn.py:99:21
  return (%input_.7)

graph(%self : __torch__.ANIForce,
      %positions.1 : Tensor):
  %10 : None = prim::Constant()
  %4 : float = prim::Constant[value=10]() # test.py:18:46
  %6 : int = prim::Constant[value=0]() # test.py:18:71
  %15 : float = prim::Constant[value=2625.5]() # test.py:19:15
  %2 : __torch__.torchani.nn.Sequential = prim::GetAttr[name="model"](%self)
  %3 : Tensor = prim::GetAttr[name="species"](%self)
  %7 : Tensor = aten::unsqueeze(%positions.1, %6) # test.py:18:51
  %8 : Tensor = aten::mul(%7, %4) # <string>:3:9
  %9 : (Tensor, Tensor) = prim::TupleConstruct(%3, %8)
  %12 : NamedTuple(species : Tensor, energies : Tensor) = prim::CallMethod[name="forward"](%2, %9, %10, %10) # test.py:18:20
  %13 : Tensor, %energy.1 : Tensor = prim::TupleUnpack(%12)
  %17 : Tensor = aten::mul(%energy.1, %15) # <string>:3:9
  return (%17)
```

I think what you are seeing is a PyTorch bug which has already been fixed by the latest PyTorch. Could you try upgrading your PyTorch to the latest nightly build and see if the error is still there?

**Comment by peastman** [comment]
Yes, installing the latest PyTorch nightly fixed it.  I'm glad it was that simple.  Thanks!

**Comment by peastman** [comment]
Than again, maybe I spoke too soon.  I can now convert the model to TorchScript.  But when I try to load it in (using the latest nightly build of LibTorch) it fails with this error:

```
Unexpected right-hand found in assignment in class body. This is not yet supported.:
Serialized   File "code/__torch__/torchani/aev.py", line 13
  EtaA : Tensor
  Zeta : Tensor
  aev_length : Final[int] = 384
                            ~~~ <--- HERE
  sizes : Final[Tuple[int, int, int, int, int]] = (4, 16, 64, 32, 320)
  angular_sublength : Final[int] = 32
```

**Comment by zasdfgbnm** [comment]
@peastman This sounds like another bug. Could you upload your saved module and a minimum piece of libtorch code to reproduce this? I don't have any experience with libtorch, so it's hard for me to reproduce it myself.

**Comment by peastman** [comment]
The module is at https://www.dropbox.com/s/r6x8bqdc4tldwop/model.pt?dl=0.  You should be able to reproduce the problem with simply

```c++
#include <torch/script.h>

int main() {
    torch::jit::load("model.pt");
    return 0;
}
```

On the other hand, writing `torch.jit.load("model.pt")` in Python does work.  So this may be some sort of inconsistency between the latest nightly builds of the Python and C++ libraries.

**Comment by zasdfgbnm** [comment]
@peastman Great! Thanks for the help and I am able to reproduce it using a minimal script:

```python
import torch
from torch.jit import Final
print(torch.__version__)

class Model(torch.nn.Module):
    a: Final[int]

    def __init__(self):
        super().__init__()
        self.a = 5

    def forward(self, x):
        return x

m = torch.jit.script(Model())
torch.jit.save(m, 'model.pt')
torch.jit.load('model.pt')
```

**Comment by zasdfgbnm** [comment]
@peastman I will file a bug report to PyTorch

**Comment by zasdfgbnm** [comment]
But to solve your problem, for now, you could remove all the `Final` in https://github.com/aiqm/torchani/blob/master/torchani/aev.py#L309 manually and it should be working.

**Comment by peastman** [comment]
Thanks!  I'll give that a try.

**Comment by peastman** [comment]
Unfortunately, removing the `Final` annotations from aev.py isn't enough.  If I do that, I just get the same error from a different class that's internal to PyTorch:

```
Exception: 
Unexpected right-hand found in assignment in class body. This is not yet supported.:
Serialized   File "code/__torch__/torch/nn/modules/linear.py", line 6
  weight : Tensor
  bias : Tensor
  out_features : Final[int] = 160
                              ~~~ <--- HERE
  in_features : Final[int] = 384
  def forward(self: __torch__.torch.nn.modules.linear.Linear,
```

So it looks like it will require a fix to PyTorch.

**Comment by zasdfgbnm** [comment]
@peastman OK, let's just waiting for what people say at https://github.com/pytorch/pytorch/issues/31960

**Comment by driazati** [comment]
This looks like it's probably a versioning issue on our (PyTorch) end, this code works fine for me on a libtorch built on PyTorch master but fails in nightly libtorch. You could try [building from source](https://github.com/pytorch/pytorch#from-source) in the meantime while we get this fixed.

**Comment by driazati** [comment]
This should be fixed now (see pytorch/pytorch#31960), the nightly build is now up to date and fixes this bug in my local testing.

**Comment by zasdfgbnm** [comment]
@peastman Nightly libtorch build has been fixed officially by PyTorch. Could you please give it a try?

**Comment by peastman** [comment]
It works great.  Thank you, you're awesome!
