### ISSUE TITLE
Split of dataset is not stored in the example training script

### ISSUE THREAD

**Issue by zasdfgbnm** [aiqm/torchani#443]
In the training example, we are saving the latest models so that we can resume from that, but the split of the dataset is regenerated and different every run.

https://github.com/aiqm/torchani/blob/master/examples/nnp_training.py
https://github.com/aiqm/torchani/blob/master/examples/nnp_training_force.py

**Comment by IgnacioJPickering** [comment]
Why is this an issue?

**Comment by zasdfgbnm** [comment]
Data pollution. If you restart from a checkpoint, then the training/validation/testing split will be different, that is, your testing set will contain data that you have used for training.

**Comment by IgnacioJPickering** [comment]
Ahh, makes sense, I usally split once and then pickle the result so I never run into that issue but I see how that could be a problem. Maybe there is a better way

**Comment by IgnacioJPickering** [comment]
Solved with #548
