### ISSUE TITLE
Memory consumption on CPU

### ISSUE THREAD

**Issue by wiederm** [aiqm/torchani#468]
Dear torchani developers!

I have been running a simple test with torchani 1.2 and torch 1.4.0 in which I calculate the energies of 100 molecules each with 10 heavy atoms in a batch. My coordinate tensor has the size `[100, 40, 3]` and I notice that the energy calculation has a substantial memory footprint, taking around 4 GB of RAM.
Here is the output of the memory profiling (running this script https://gist.github.com/wiederm/4b8ebae991f26293905dd701f79f463c):

```
Line #    Mem usage    Increment   Line Contents
================================================
     5    143.9 MiB    143.9 MiB   @profile
     6                             def setup():
     7    143.9 MiB      0.0 MiB       nr_of_methans = 10
     8    143.9 MiB      0.0 MiB       nr_of_frames = 100
     9    143.9 MiB      0.0 MiB       device = 'cpu'
    10    167.3 MiB     23.4 MiB       model = torchani.models.ANI1ccx(periodic_table_index=True).to(device)
    11    167.3 MiB      0.0 MiB       coordinates = torch.tensor([[[0.03192167, 0.00638559, 0.01301679],
    12    167.3 MiB      0.0 MiB                                   [-0.83140486, 0.39370209, -0.26395324],
    13    167.3 MiB      0.0 MiB                                   [-0.66518241, -0.84461308, 0.20759389],
    14    167.3 MiB      0.0 MiB                                   [0.45554739, 0.54289633, 0.81170881],
    15    167.3 MiB      0.0 MiB                                   [0.66091919, -0.16799635, -0.91037834]]*nr_of_methans]*nr_of_frames,
    16    167.3 MiB      0.0 MiB                               requires_grad=True, device=device)
    17    167.3 MiB      0.0 MiB       species = torch.tensor([[6, 1, 1, 1, 1]*nr_of_methans]*nr_of_frames, device=device)
    18   4016.9 MiB   3849.7 MiB       energy = model((species, coordinates)).energies
```

I am wondering if:
- this is expected behaviour?
- there is a possibility to minimize the RAM memory consumption?

thank you very much for you time!

**Comment by IgnacioJPickering** [comment]
I will double check this and I'll get back to you, but I believe this is possible. If you are inputing a tensor of size [100, 40, 3] then this is effectively the same as 1 molecule with 4000 atoms, and tensors do take up quite a large chunk of memory.

**Comment by IgnacioJPickering** [comment]
I rechecked your result and your results seem correct, it currently takes about ~ 4 GB of ram to calculate an input of that size.

**Comment by wiederm** [comment]
Thanks for checking! I will close this issue then!

**Comment by IgnacioJPickering** [comment]
Quick comment, this result I told you is true for the ANI 2x network
The ANI 1x or ANI 1ccx networks actually take much less ram for this input ( ~1.7 GB)
So if you are worried about memory consumption take into account using less elements can improve this.
