### ISSUE TITLE
some questions about the system

### ISSUE THREAD

**Issue by hjh19970102** [aiqm/torchani#497]
Dear  developers ,
     I saw the training sets in this work including single molecule,I wonder if I could train something like molecular cluster.If I want to use  molecular cluster as my training set,do the SMILES strings still work?
Or,does torchani sopport the format of the training set in other style?
Thank you very much.

**Comment by farhadrgh** [comment]
Hi, 
Yes, you can use molecular clusters in your training as long as your GPU memory allows. However, TorchANI does not use SMILES as input. Please refer to a [previous discussion](https://github.com/aiqm/torchani/issues/360) about the format of the dataset used by TorchANI. An example of datasets used for training can be found under `torchani/dataset/ani-1x/sample.h5` once you execute [`download.sh`](https://github.com/aiqm/torchani/blob/master/download.sh).

**Comment by hjh19970102** [comment]
I really appreciate it for your introductions.
One more question,for a simple example about water dimers,can I write something like this?
coordinates:  [[ ... ... ...]
  [ ... ... ... ]]
species: ['H', 'H', 'O','H', 'H', 'O']
And then convert to .h5.
And I wonder if I could train something like periodic system,if that how to describ the box size?If a box concluding 16 waters.
Thank you so much.

**Comment by hjh19970102** [comment]
I really appreciate it for your introductions.
One more question,for a simple example about water dimers,can I write something about coordinates and species like this?
coordinates: [[ ... ... ...]
[ ... ... ... ]]
species: ['H', 'H', 'O','H', 'H', 'O']
And then convert to .h5.
And I wonder if I could train something like periodic system,if that how to describ the box size?If a box concluding 16 waters.
Thank you so much.

**Comment by farhadrgh** [comment]
No problem, Yes, so if you have water dimer data, it will be considered one data point which has 6 species, 6x3 coordinates, and one energy value. Similarly, a wrapped box concluding 16 water molecules will be considered as one data point. You will need to wrap the periodic system and come up with a unique system (no PBC images).

**Comment by hjh19970102** [comment]
Oh,I see ,thanks very much.
