### ISSUE TITLE
specify path to ANI2x parameter location

### ISSUE THREAD

**Issue by mhellstr** [aiqm/torchani#499]
Hello,

torchani.models.ANI2x() downloads and unzips parameters into site-packages/torchani/resources, but this means that you cannot cleanly pip3 uninstall torchani, since site-packages/torchani is then left on disk. As a consequence, after "uninstalling" torchani, you can still import torchani without error but not use it for anything.

It would be quite nice if one could specify a path from which to read the parameters (and download parameters to if the path does not exist), e.g. torchani.models.ANI2x(parameter_path='/my/preferred_path/ani2x').

**Comment by farhadrgh** [comment]
Hi,
Thanks for pointing this out. I guess one quick solution is to skip downloading into `site-packages` and store them in `~/.local/torchani/`. That will result in a clean uninstall
