### ISSUE TITLE
Recommended methods for solvation and dispersion correction?

### ISSUE THREAD

**Issue by atom-moyer** [aiqm/torchani#504]
Hi all,

Thanks for making this project open source. It is great example of science and engineering.

For practical applications, I believe that it is important to model not just the gas phase energies/derivatives, but also the solvation and dispersion corrected energies/derivatives (correct me if I am wrong).  Do you all have a recommendation on how to best do this?  I have used the dispersion correction from the Grimme's Lab (dft-D4). I have not found a solvation correction. I have read the papers, but I did not find any comments that address this issue.

I have been using AIMNet as this has the solvation correction baked into the model.

Thanks,
Adam

**Comment by IgnacioJPickering** [comment]
Hello @atom-moyer. Currently Torchani doesn't implement any solvation or dispersion correction. Adding Grimme's dispersion correction should be compatible with the model but solvation models can't really be managed by the network out of the box.
