### ISSUE TITLE
accessing all predictions from an ensemble

### ISSUE THREAD

**Issue by mhellstr** [aiqm/torchani#505]
Hello,

I was wondering how I could access each individual NN prediction (or the standard deviation + ensemble size) if I make a prediction with an ensemble like e.g. ANI2x?

(to clarify: it would be nice to be able to get the individual predictions or the summary statistics without manually needing to loop over the constituent networks)

**Comment by hadim** [comment]
I would also be interested in having access to the latent space of the molecule representation. At the atomic level as well as the whole molecule level.

**Comment by hadim** [comment]
friendly ping for @zasdfgbnm

**Comment by IgnacioJPickering** [comment]
I'm closing this since we have an API to access each individual prediction now. There are no plans to implement access to the latent space representation right now.
