### ISSUE TITLE
The source pypi archive is not conventional

### ISSUE THREAD

**Issue by hadim** [aiqm/torchani#507]
The source archive at https://files.pythonhosted.org/packages/cb/84/b4adcce3c0d961daf5376e504826dece67ba06d9c1c92ccbaa591936b7a1/torchani-2.1.1.linux-x86_64.tar.gz is required to build a conda package of torchani (see https://github.com/conda-forge/staged-recipes/pull/12242).

Its structure is not conventional: `https://files.pythonhosted.org/packages/cb/84/b4adcce3c0d961daf5376e504826dece67ba06d9c1c92ccbaa591936b7a1/torchani-2.1.1.linux-x86_64.tar.gz`

The source tarball should contain the source repo with setup.py file others. See this one as an example https://files.pythonhosted.org/packages/23/b0/ff0f4ffa3da1ddb242a295d5d19dd1775f567ad73a6ea7474eaa55e04836/scikit-learn-0.23.1.tar.gz

**Comment by hadim** [comment]
Thanks @farhadrgh . I will finish the conda package once you have released a new version to pypi. Please ping me here!

**Comment by zasdfgbnm** [comment]
@hadim A new release is pushed to PyPI. Please test and let me know if it still has a problem :)

**Comment by hadim** [comment]
The package is now available on conda-forge: `conda install -c conda-forge torchani` (haven't tested it yet).

**Comment by isayev** [comment]
@hadim really cool, thanks! Does not (yet?) work on ubuntu :

`conda install -c conda-forge torchani`

fails with

```

PackagesNotFoundError: The following packages are not available from current channels:

  - torchani

```

but the package is there: https://anaconda.org/conda-forge/torchani

**Comment by hadim** [comment]
Yes, you just need to wait for the index to be updated. Check again in ~10min.
