### ISSUE TITLE
CUAEV cuda 11 error

### ISSUE THREAD

**Issue by yueyericardo** [aiqm/torchani#549]
As mensioned at https://github.com/aiqm/torchani/pull/516#issuecomment-718425316

**Comment by IgnacioJPickering** [comment]
@yueyericardo is this still an issue? I have cuda 11.2 and I am not having problems with cuaev

**Comment by yueyericardo** [comment]
Oh, really? I didn't test it. Let me try.

**Comment by yueyericardo** [comment]
Fixed
