### ISSUE TITLE
NMR examples

### ISSUE THREAD

**Issue by shubbey** [aiqm/torchani#558]
Hello,
I am attempting to compute NMR chemical shifts from the ANI network, as noted in the latest paper.  I was wondering if you had any publicly available examples of this as I fear I am not doing this in the most straightforward manner.  Thanks and apologies if this is the wrong place to post.

**Comment by IgnacioJPickering** [comment]
Hello Shubbey, we are not planning on adding NMR examples for the time being, I think the best thing regarding this is to contact @farhadrgh or @zasdfgbnm directly via email, they may be able to offer some insights into the NMR shift calculations.
