### ISSUE TITLE
Incompatible/Unclear documentation for loading models

### ISSUE THREAD

**Issue by ajsmit24** [aiqm/torchani#567]
I am attempting to train a custom model using the code from [this](https://aiqm.github.io/torchani/examples/nnp_training.html) tutorial which saves the best model as 'best.pt' using `torch.save`. However, I was attempting to load this model based on [this](https://aiqm.github.io/torchani/examples/jit.html) documentation, but it implements jit which does not seem to be compatible. Therefore I was wondering how one would load and use the best.pt model.

**Comment by IgnacioJPickering** [comment]
@ajsmit24 both the builtin models and models that you create using torchani.nn.Sequential as in the first tutorial you linked are JIT compatible, I'm not sure what you mean, are you having issues with JIT?
