### ISSUE TITLE
Support for Ions

### ISSUE THREAD

**Issue by tfisher013** [aiqm/torchani#593]
Hi,

I wanted to check whether the current version of TorchANI has support for ionic species and, if so, to what extent. I looked in the documentation but couldn't find anything relating to ions.

Thanks for your help!
Thomas

**Comment by IgnacioJPickering** [comment]
Hello @tfisher013, currently ANI does not support ions to any extent, this is a topic of current research in our group

**Comment by tfisher013** [comment]
Thanks for your reply, Ignacio! I appreciate it.
