### ISSUE TITLE
Addition of standard deviation for ensemble models. 

### ISSUE THREAD

**Issue by kryczko** [aiqm/torchani#594]
Currently, the pre-trained models return the averaged energies for the given ensemble. I'm wondering what would be the best way to also include the standard deviation within the forward function.

**Comment by yueyericardo** [comment]
Hi, 

You could use the following code to get the predicted energy from each model, and calculate the std
```python
model.members_energies((species, coordinates)).energies
```

**Comment by kryczko** [comment]
Perfect! Thanks so much!
