### ISSUE TITLE
The conversion of the ANI-2x model to TorchScript fails with PyTorch 1.9

### ISSUE THREAD

**Issue by raimis** [aiqm/torchani#598]
The conversion of the ANI-2x model to TorchScript fails with PyTorch 1.9:

```python
import torch
import torchani

print(torch.__version__)
print(torchani.__version__)

torch.jit.script(torchani.models.ANI2x())
```

```bash
$ conda install -c conda-forge pytorch=1.9 torchani
$ python debug.py 
1.9.0
2.2
Traceback (most recent call last):
  File "debug_torchani.py", line 7, in <module>
    torch.jit.script(torchani.models.ANI2x())
  File "/shared/raimis/opt/miniconda/envs/tmp_torchani/lib/python3.8/site-packages/torch/jit/_script.py", line 1096, in script
    return torch.jit._recursive.create_script_module(
  File "/shared/raimis/opt/miniconda/envs/tmp_torchani/lib/python3.8/site-packages/torch/jit/_recursive.py", line 412, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/shared/raimis/opt/miniconda/envs/tmp_torchani/lib/python3.8/site-packages/torch/jit/_recursive.py", line 474, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/shared/raimis/opt/miniconda/envs/tmp_torchani/lib/python3.8/site-packages/torch/jit/_script.py", line 497, in _construct
    init_fn(script_module)
  File "/shared/raimis/opt/miniconda/envs/tmp_torchani/lib/python3.8/site-packages/torch/jit/_recursive.py", line 437, in init_fn
    cpp_module.setattr(name, orig_value)
RuntimeError: Could not cast attribute 'rev_species' to type Dict[Tensor, int]: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

But it works with PyTorch 1.8:
```bash
$ conda install -c conda-forge pytorch=1.8 torchani
$ python debug.py
1.8.0
2.2
```

**Comment by yueyericardo** [comment]
ping @IgnacioJPickering

**Comment by IgnacioJPickering** [comment]
ohh yes, thanks for the heads up! I will merge this tomorrow, I hadn't
noticed this stopped working in the public repo.

**Comment by yueyericardo** [comment]
Hi, sorry for the confusion. The problem here is actually because the conda-forge torchani is too old (which is not maintained by us), the code in the master branch is already fixed.

**Comment by yueyericardo** [comment]
Hi, we will maintain the conda-forge torchani from now on, and will let you know once it is done.

**Comment by yueyericardo** [comment]
Will be ready once https://github.com/conda-forge/torchani-feedstock/pull/2 got merged.

**Comment by yueyericardo** [comment]
@raimis For conda-forge torchani, we would like to support only latest pytorch and cuda, but to be compatible with openmm, it currently is building with the following matrix. So let me know if we could remove some versions of pytorch, for example 1.8.0 or 1.9.0.

pytorch
- 1.8.0
- 1.9.0
- 1.9.1
- 1.10.0

and cuda
- 10.2
- 11.0
- 11.1
- 11.2

**Comment by yueyericardo** [comment]
Hi Raimondas, torchani 2.2.1 is available at [conda-forge](https://anaconda.org/conda-forge/torchani) now. It currently support all matrix I mentioned in last comment. The version you previously used on conda-forge is pretty old, let me know if this new version works with nnpops.

**Comment by raimis** [comment]
OK! I'll try.

**Comment by raimis** [comment]
@yueyericardo I tried TorchANI 2.2.1. The conversion to TorchScript has been fixed, but still there is an issue with serialisation:

```python
import torch
import torchani

print(torch.__version__)
print(torchani.__version__)

torch.jit.script(torchani.models.ANI2x()).save('model.pt')
```

```
1.10.0
2.2.1
Traceback (most recent call last):
  File "/home/raimis/NNPOps.git/debug.py", line 7, in <module>
    torch.jit.script(torchani.models.ANI2x()).save('model.pt')
  File "/home/raimis/opt/miniconda/envs/nnpops/lib/python3.9/site-packages/torch/jit/_script.py", line 686, in save
    return self._c.save(str(f), **kwargs)
RuntimeError: Cannot serialize custom bound C++ class __torch__.torch.classes.cuaev.CuaevComputer. Please define serialization methods via def_pickle() for this class.
```

**Comment by raimis** [comment]
@yueyericardo thanks for your effort! The issue is solved and the solution integrated into NNPOps (https://github.com/openmm/NNPOps/releases/tag/v0.1)
