### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by mikemhenry** [aiqm/torchani#620]
~It has been a year and half since the last release~ (Sorry! I now see Nov 3, 2021 was the last release) and there have been some PRs like this one https://github.com/aiqm/torchani/pull/603 that make torchani much easier to install in a modern pytorch stack.

**Comment by yueyericardo** [comment]
Sorry for the long wait, New version has been released. Waiting for Conda-forge tests to be passed.

**Comment by mikemhenry** [comment]
Thank you so much!
