### ISSUE TITLE
ANI-2x dataset files

### ISSUE THREAD

**Issue by rschireman** [aiqm/torchani#626]
Hi all,

I'm not really sure where to ask this, but is there anyway we could get access to the .h5 file for the ANI-2x dataset for benchmarking models?

**Comment by roitberg** [comment]
Hi. Email me directly to roitberg@ufl.edu and we can share them with you

**Comment by rschireman** [comment]
sounds great!

**Comment by rschireman** [comment]
I'll leave my academic email here too and close the issue!

rschirem@uvm.edu

Thanks again!
