### ISSUE TITLE
Are you sure the energies are in Hartree?

### ISSUE THREAD

**Issue by UnixJunkie** [aiqm/torchani#637]
```python
model((species, coordinates)).energies.item()
```
I wonder if some scaling factor of like 1/100_000 is not missing somewhere.

But, it might also be that my conformers should first be minimized in your ~QM FF before
I look at the scores they get.

**Comment by yueyericardo** [comment]
Hi Francois, I confirm that the energy output from the model is indeed in hartree.
To clarify in the document [Computing Energy and Force Using Models Inside Model Zoo — TorchANI 2.2.3 documentation](https://aiqm.github.io/torchani/examples/energy_force.html), you'll observe that the energy for CH4 is approximately -40.45979 Hartree.

I would suggest verifying the unit of your coordinates, they should be in Angstrom.

**Comment by UnixJunkie** [comment]
I can reproduce your CH4 energy, thanks.
